# Generated by Django 2.0.6 on 2018-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='planodeestudo',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
