# Generated by Django 2.0.6 on 2018-07-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='plano',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.PlanoDeEstudo'),
            preserve_default=False,
        ),
    ]
