# Generated by Django 2.0.6 on 2018-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180703_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assunto',
            unique_together={('disciplina', 'nome')},
        ),
    ]
