# Generated by Django 2.0.6 on 2018-07-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180703_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assunto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
